### ISSUE TITLE
Are PRs welcome or is this more of a personal project?

### ISSUE THREAD

**Issue by tekknolagi** [eatonphil/pyc#1]
I saw this pop up on GitHub Explore (I think because I follow you?) and it looks interesting. I was wondering if you would be alright with me submitting the odd pull request if I find the time.

**Comment by eatonphil** [comment]
Follow IRC rules please! Don't ask to ask :) just open a PR if there's something that interests you to contribute to!

**Comment by tekknolagi** [comment]
Sounds reasonable. Can you please add a license?
